<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Title;
use Hyva\Theme\ViewModel\CurrentCategory;

$currentCategoryViewModel = $viewModels->require(CurrentCategory::class);
$currentCategory = $currentCategoryViewModel->fetch();
$categoryName = $currentCategory->getName() ? $currentCategory->getName() : $block->getPageHeading();

/** @var Escaper $escaper */
/** @var Title $block */

$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : 'text-3xl';
$titleHtml = '';

if (trim((string)$block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" ' . $block->getAddBaseAttribute() . '>' . $escaper->escapeHtml($categoryName) . '</span>';
}
if ($titleHtml): ?>
    <div class="category-inner-title <?= /** @noEscape */ $cssClass ?>">
        <h1 class="page-title title-font text-3xl leading-[33px] font-semibold mb-6 lg:text-4xl lg:leading-10"
            <?php if ($block->getId()): ?> id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>>
            <?= /* @noEscape */ $titleHtml ?>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>