<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */

$product = $block->getProduct();

$productName = $block->getProduct()->getName();

?>
<div class="page-title-section font-bold text-3xl flex justify-between mt-4">
    <h1>
        <?= $productName = $block->getProduct()->getName(); ?>
    </h1>
    <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/view/addtowishlist.phtml")->toHtml() ?>
</div>
<section class="text-ALED-Black body-font md:mb-6">
    <div class="flex pb-6 md:pb-2 py-6 md:py-12 lg:flex-row flex-col items-center">
        <div class="grid grid-rows-auto grid-cols-1 md:gap-x-5 md:grid-cols-[100%_minmax(0,_1fr)] md:grid-rows-[min-content_minmax(0,_1fr)] w-full">
            <?= $block->getChildHtml('product.media') ?>
        </div>
    </div>
</section>
<section>
    <?= $block->getChildHtml('product.info') ?>
</section>
<section class="w-full md:mb-10 mb-8">
<?= $block->getChildHtml('product.info.details'); ?>
<?= $block->getChildHtml('product.static.section'); ?>

</section>
<section class="w-full md:mb-10 mb-8">
<?php if($product->getTypeId() == 'simple'): ?>
<?= $block->getChildHtml('product.info.simpleproduct'); ?>
<?php endif; ?>
</section>
<section class="w-full md:mb-10 mb-8">
    <?= $block->getChildHtml('product_options_wrapper_bottom') ?>
</section>
<section class="w-full md:mb-10 mb-8">
    <?= $block->getChildHtml('spareparts') ?>
    <?= $block->getChildHtml('accessories') ?>
    <?= $block->getChildHtml('related') ?>
    <?= $block->getChildHtml('upsell') ?>
    <?= $block->getChildHtml('review_list') ?>
    <?= $block->getChildHtml('review_form') ?>
</section>